In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
precip = pd.read_csv('datos_climatologicos.csv')

In [25]:
precip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21408 entries, 0 to 21407
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Fecha      21408 non-null  object
 1   Precip_mm  21408 non-null  object
 2   Evap_mm    21408 non-null  object
 3   TMAX_C     21408 non-null  object
 4   TMIN_C     21408 non-null  object
dtypes: object(5)
memory usage: 836.4+ KB

In [26]:
precip[precip['Precip_mm'] == 'NULO']

            Fecha Precip_mm Evap_mm TMAX_C TMIN_C
3776   21/06/1969      NULO     2.5   NULO   NULO
3814   01/08/1969      NULO    2.73   33.5     22
9234   03/06/1984      NULO    NULO   NULO   NULO
14986  16/04/2000      NULO    NULO   NULO   NULO
15153  12/10/2000      NULO    3.04     33   22.5
...           ...       ...     ...    ...    ...
21225  28/02/2019      NULO     7.9   NULO   NULO
21375  28/10/2019      NULO    NULO   NULO   NULO
21376  31/10/2019      NULO    NULO   NULO   NULO
21405  30/11/2019      NULO    3.55     37   24.5
21407  02/12/2019      NULO    NULO   NULO   NULO

[79 rows x 5 columns]

In [27]:
precip['Precip_mm'] = precip['Precip_mm'].replace('NULO', 0)

In [28]:
precip['Precip_mm'] = precip['Precip_mm'].astype(float)
precip['Fecha'] = pd.to_datetime(precip['Fecha'], format='%d/%m/%Y')

In [29]:
lluvias = precip[precip['Precip_mm'] >= 50][['Fecha','Precip_mm']]

In [30]:
lluvias

           Fecha  Precip_mm
90    1959-05-02       76.0
115   1959-05-27       80.0
164   1959-07-15       70.0
168   1959-07-19       55.0
169   1959-07-20       65.0
...          ...        ...
21312 2019-05-26       57.0
21317 2019-05-31       55.0
21333 2019-09-16      147.2
21343 2019-09-26       53.2
21369 2019-10-22       80.0

[608 rows x 2 columns]

In [31]:
lluvias_2 = lluvias.sort_values(by = 'Precip_mm', ascending = False)

In [32]:
lluvias_2.head(15)

           Fecha  Precip_mm
16779 2005-10-05      457.8
14430 1998-09-07      274.0
5690  1974-09-20      239.1
14431 1998-09-08      225.6
17709 2008-06-03      212.5
10773 1988-09-02      210.0
2000  1964-07-24      208.0
19406 2013-05-29      203.2
1228  1962-06-13      200.5
1694  1963-09-22      193.1
7150  1978-09-19      187.8
16778 2005-10-04      182.3
18493 2010-09-26      170.0
19764 2014-06-03      167.5
10771 1988-08-31      166.2

In [33]:
# crear intervalos de 50 en 50
bins = range(50, 501, 50)

In [34]:
labels = ['50-100', '100-150', '150-200', '200-250','250-300', '300-350', '350-400', '400-450', '450-500']

In [35]:
lluvias_2['intervalos'] = pd.cut(lluvias_2['Precip_mm'], bins=bins, labels=labels, include_lowest=True)

In [36]:
lluvias_2

           Fecha  Precip_mm intervalos
16779 2005-10-05      457.8    450-500
14430 1998-09-07      274.0    250-300
5690  1974-09-20      239.1    200-250
14431 1998-09-08      225.6    200-250
17709 2008-06-03      212.5    200-250
...          ...        ...        ...
17710 2008-06-04       50.0     50-100
18733 2011-06-03       50.0     50-100
18411 2010-07-06       50.0     50-100
3377  1968-05-18       50.0     50-100
20650 2017-05-12       50.0     50-100

[608 rows x 3 columns]

In [37]:
lluvias_2.to_csv("lluvias_2_editado.csv", index=False)

In [38]:
conteo = lluvias_2['intervalos'].value_counts().sort_index()
print(conteo)

intervalos
50-100     526
100-150     63
150-200     10
200-250      7
250-300      1
300-350      0
350-400      0
400-450      0
450-500      1
Name: count, dtype: int64

In [39]:
lluvias_2['Mes'] = lluvias_2['Fecha'].dt.month